kind: pipeline
name: default

steps:
  - name: publish
    image: plugins/docker
    settings:
      registry: docker.castive.dev
      repo: docker.castive.dev/drone-helm-s3
      tags: ${DRONE_BRANCH}-${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
---
kind: pipeline
name: analyse

steps:
  - name: sonar
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host: https://sonar.castive.dev
      sonar_token:
        from_secret: SONAR_TOKEN