kind: pipeline
name: default

steps:
  - name: publish
    image: plugins/docker
    settings:
      registry: docker.castive.dev
      repo: docker.castive.dev/drone-helm-s3
      tags: ${DRONE_BRANCH}-${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD